language: perl
sudo: false

perl:
  - "5.16"
  - "5.14"

install:
   - cpanm --notest --quiet Dist::Zilla@5.047
   - dzil authordeps | cpanm --quiet --notest
   - cpanm --quiet --notest --installdeps .

script:
   - dzil test
